# Generated by Django 5.0.1 on 2024-01-10 23:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natillera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('dirreccion', models.CharField(max_length=256)),
                ('telefono', models.CharField(max_length=256)),
                ('periodicidad', models.CharField(max_length=256)),
                ('codigo', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('codigo', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('natillera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.natillera')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.CharField(max_length=50)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Natillera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.natillera')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
        ),
    ]
