# Generated by Django 5.0.1 on 2024-01-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_natillera_persona_socio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='natillera',
            old_name='dirreccion',
            new_name='direccion',
        ),
    ]
