# Generated by Django 5.0.1 on 2024-01-17 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dirreccion_natillera_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='Natillera',
            new_name='natillera',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='persona',
        ),
        migrations.AddField(
            model_name='socio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='apellido',
            field=models.CharField(default='valor_predeterminado', max_length=256),
        ),
        migrations.AddField(
            model_name='socio',
            name='codigos',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AddField(
            model_name='socio',
            name='nombre',
            field=models.CharField(default='valor_predeterminado', max_length=256),
        ),
    ]
