# Generated by Django 5.0.1 on 2024-01-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_socio_celular_socio_ciudad_socio_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='capital',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
