# Generated by Django 5.0.1 on 2024-02-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_socio_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_cuota',
            field=models.DateField(blank=True, null=True),
        ),
    ]
