# Generated by Django 5.0.1 on 2024-02-07 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_socio_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_evento', models.CharField(max_length=256)),
                ('fecha_inicio', models.DateField()),
                ('descripcion', models.CharField(max_length=256)),
                ('natillera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.natillera')),
            ],
        ),
    ]
