# Generated by Django 5.0.1 on 2024-02-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='deuda',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
