# Generated by Django 5.0.1 on 2024-02-14 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_socio_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='deuda',
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('deuda', models.IntegerField(blank=True, null=True)),
                ('cuota', models.IntegerField(blank=True, null=True)),
                ('nota_o_descripcion', models.CharField(blank=True, default='nada', max_length=265, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socio')),
            ],
        ),
    ]
