# Generated by Django 5.0.1 on 2024-02-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_socio_deuda_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='tipo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
