# Generated by Django 5.0.1 on 2024-02-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_eventos_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='tipo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
