# Generated by Django 5.0.1 on 2024-02-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_eventos_tipo_prestamo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cantidad_cuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
