# Generated by Django 5.0.1 on 2024-02-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_prestamo_cantidad_cuotas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='tipo',
        ),
    ]
