# Generated by Django 5.0.1 on 2024-02-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_prestamo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='tipo_pretamo',
            field=models.CharField(blank=True, default='nada', max_length=256, null=True),
        ),
    ]
